name: ecommerce
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'




# ----PACKAGES ---


dependencies:
  flutter:
    sdk: flutter


# Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  connectivity_plus: ^6.0.3

  
# Icons
  icon: ^2.2.1
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  google_sign_in: ^6.2.1


  # ---PACKAGES END--------


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icons/icons8-heart-50.png"
  

  
  
  
  flutter_lints: ^3.0.2





flutter:


  
  uses-material-design: true

  # LOCAL ASSETS ----
  assets:
    - assets/icons/
    - assets/images/on_boarding_images/gif1.png
    - assets/images/on_boarding_images/gif2.gif
    - assets/images/on_boarding_images/jif3.jpeg
    - assets/images/reviews/review_profile.jpeg
    - assets/icons/brands/nikeicon.png
    - assets/logo/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/images/payment_methods/
    - assets/fonts/

  # --- LOCAL FONTS ----#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 800