// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:

        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVFjvIoUMVsf5z_P0aX9SdzWeHZdgrwP4',
    appId: '1:954950422354:web:52a9efb00ad4ff2d14748b',
    messagingSenderId: '954950422354',
    projectId: 'ecommerceapp-5921d',
    authDomain: 'ecommerceapp-5921d.firebaseapp.com',
    storageBucket: 'ecommerceapp-5921d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa3xeUbkPNALC5q-7d5FRyxzEKl7MRVOc',
    appId: '1:954950422354:android:1d5c233c619551a914748b',
    messagingSenderId: '954950422354',
    projectId: 'ecommerceapp-5921d',
    storageBucket: 'ecommerceapp-5921d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVr0On63MB5NF_MRP2EYo2yyoV2P4ocU',
    appId: '1:954950422354:ios:bd4c1ce88de2b8a214748b',
    messagingSenderId: '954950422354',
    projectId: 'ecommerceapp-5921d',
    storageBucket: 'ecommerceapp-5921d.appspot.com',
    iosBundleId: 'com.ecommerce.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVFjvIoUMVsf5z_P0aX9SdzWeHZdgrwP4',
    appId: '1:954950422354:web:b85530478732075c14748b',
    messagingSenderId: '954950422354',
    projectId: 'ecommerceapp-5921d',
    authDomain: 'ecommerceapp-5921d.firebaseapp.com',
    storageBucket: 'ecommerceapp-5921d.appspot.com',
  );
}
